# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  # - "first.rules"
  # - "second.rules"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'system'
    static_configs:
      - targets:
          - 'console.admin.radiobretzel.org:9100'
          - 'jobmaster.admin.radiobretzel.org:9100'
          - 'fw.admin.radiobretzel.org:9100'
          - 'ns1.dmz.radiobretzel.org:9100'
          - 'www.dmz.radiobretzel.org:9100'
          - 'docker-01.docker.radiobretzel.org:9100'
          - 'proxy-01.public.radiobretzel.org:9100'

  - job_name: 'firewall'
    static_configs:
      - targets:
          - '10.12.10.254:9100'

  - job_name: 'webservers'
    static_configs:
      - targets:
          - 'www.dmz.radiobretzel.org:9113'
          - 'proxy-01.public.radiobretzel.org:9113'

  - job_name: 'gitlab'
    static_configs:
      - targets:
          - 'gitlab.dmz.radiobretzel.org:9100'  # node_exporter
          - 'gitlab.dmz.radiobretzel.org:9168'  # gitlab_monitor
          - 'gitlab.dmz.radiobretzel.org:9187'  # postgres_exporter

  - job_name: 'mattermost'
    static_configs:
      - targets:
          - 'chat.dmz.radiobretzel.org:9100'  # node_exporter
          - 'chat.dmz.radiobretzel.org:9187'  # postgres_exporter
